spring.application.name=Revisao-3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/Revisao3
spring.datasource.username=root
spring.datasource.password=